---
- hosts: all_nodes
  roles:
  - check_connection_to_infras

- hosts: control_plane
  roles:
  - setup_control_plane
  - k8s_status
  - download_admin_k8sconfig

- hosts: control_plane
  roles:
  - setup_worker_nodes
  - k8s_status

- hosts: control_plane
  roles:
  - k8s_status